# Generated by Django 5.1.7 on 2025-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_pattern',
            name='maximum_marks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_pattern',
            name='no_of_questions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
