# Generated by Django 5.1.7 on 2025-05-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exam_pattern_maximum_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_pattern',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='exam_pattern',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='subject',
            name='total_marks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
