# Generated by Django 5.1.7 on 2025-05-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exam_pattern_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='total_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_questions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
