# Generated by Django 5.1.7 on 2025-05-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subject_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_pattern',
            name='duration',
            field=models.FloatField(),
        ),
    ]
