# Generated by Django 5.1.7 on 2025-05-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_syllabus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabus'},
        ),
    ]
