# Generated by Django 5.1.7 on 2025-05-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_syllabus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyq',
            name='course',
        ),
        migrations.AddField(
            model_name='pyq',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='core.subject'),
            preserve_default=False,
        ),
    ]
