# Generated by Django 5.1.7 on 2025-06-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pyq_course_pyq_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_courses', to='core.course')),
            ],
        ),
    ]
