# Generated by Django 6.0.3 on 2026-06-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_question_choice_quiz_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('paper_link', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_papers', to='core.subject')),
            ],
            options={
                'verbose_name_plural': 'Solved Papers',
            },
        ),
    ]
