# Generated by Django 6.0.3 on 2026-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_solvedpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=255)),
                ('form_fee', models.IntegerField()),
                ('apply_date', models.DateField()),
                ('last_date', models.DateField()),
                ('official_website', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('apply_link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Job Vacancies',
            },
        ),
    ]
