# Generated by Django 6.0.3 on 2026-07-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jobvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
