# Generated by Django 6.0.3 on 2026-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quiz_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvedpaper',
            options={'verbose_name': 'Past Paper / Answer Key', 'verbose_name_plural': 'Past Papers & Answer Keys'},
        ),
        migrations.AddField(
            model_name='solvedpaper',
            name='answer_key_link',
            field=models.URLField(blank=True, help_text='Google Drive or AWS S3 link for the Answer Key.', max_length=1000, null=True, verbose_name='Answer Key Link'),
        ),
        migrations.AlterField(
            model_name='solvedpaper',
            name='paper_link',
            field=models.URLField(help_text='Google Drive or AWS S3 link for the Question Paper.', max_length=1000, verbose_name='Paper Link'),
        ),
        migrations.AlterField(
            model_name='solvedpaper',
            name='title',
            field=models.CharField(help_text='e.g. UPSC 2024 Prelims GS Paper', max_length=255),
        ),
        migrations.AlterField(
            model_name='solvedpaper',
            name='year',
            field=models.IntegerField(help_text='e.g. 2024'),
        ),
    ]
