# Generated by Django 6.0.3 on 2026-08-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_solvedpaper_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedpaper',
            name='linked_mock',
            field=models.ForeignKey(blank=True, help_text='Select a Mock Test to link with this paper.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_papers', to='core.quiz', verbose_name='Linked Mock Test'),
        ),
    ]
