# Generated by Django 6.0.3 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solvedpaper_linked_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. BPSC 68th Mains Result Declared', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Check your merit list and cut-off marks', max_length=500, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='category_badge',
            field=models.CharField(blank=True, help_text='e.g., BPSC, SSC, UPSC', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g., Graduation, 10th Pass', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='vacancy_count',
            field=models.CharField(blank=True, help_text='e.g., 600+ Vacancies', max_length=100, null=True),
        ),
    ]
