# Generated by Django 6.0.3 on 2026-08-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_recentupdate_jobvacancy_category_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='job_type',
            field=models.CharField(choices=[('GOVT', 'Government'), ('PRIVATE', 'Private')], default='GOVT', max_length=20),
        ),
    ]
