# Generated by Django 6.0.3 on 2026-08-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_jobvacancy_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., UPSC, SSC CGL', max_length=200)),
            ],
            options={
                'verbose_name': 'Topic-wise Exam',
                'verbose_name_plural': '1. Topic-wise Exams',
            },
        ),
        migrations.CreateModel(
            name='TopicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Ancient History, Indian Geography', max_length=200)),
            ],
            options={
                'verbose_name': 'Topic Name',
                'verbose_name_plural': '3. Topic Names',
            },
        ),
        migrations.AlterModelOptions(
            name='jobvacancy',
            options={'ordering': ['-apply_date'], 'verbose_name_plural': 'Job Vacancies'},
        ),
        migrations.CreateModel(
            name='TopicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The MCQ Question text')),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer', null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.topicname')),
            ],
            options={
                'verbose_name': 'Topic-wise Question',
                'verbose_name_plural': '4. Topic-wise Questions',
            },
        ),
        migrations.CreateModel(
            name='TopicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., History, Geography', max_length=200)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.topicexam')),
            ],
            options={
                'verbose_name': 'Topic-wise Subject',
                'verbose_name_plural': '2. Topic-wise Subjects',
            },
        ),
        migrations.AddField(
            model_name='topicname',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.topicsubject'),
        ),
    ]
