# Generated by Django 6.0.3 on 2026-08-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_topicexam_topicname_alter_jobvacancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicname',
            name='bulk_upload_json',
            field=models.TextField(blank=True, help_text='Paste JSON here to bulk upload questions. e.g., [{"text": "Q1", "choices": [{"text": "A", "is_correct": false}, ...]}]', null=True),
        ),
    ]
