# Generated by Django 6.0.3 on 2026-08-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_topicname_bulk_upload_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterialExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., UPSC, BPSC, SSC', max_length=200)),
            ],
            options={
                'verbose_name': 'Study Material Exam',
                'verbose_name_plural': '1. Study Material Exams',
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Modern History, Indian Polity', max_length=200)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_subjects', to='core.studymaterialexam')),
            ],
            options={
                'verbose_name': 'Study Material Subject',
                'verbose_name_plural': '2. Study Material Subjects',
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Chapter 1 Notes', max_length=255)),
                ('file_link', models.URLField(help_text='Google Drive or AWS S3 link to the PDF or Image', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.studymaterialsubject')),
            ],
            options={
                'verbose_name': 'Study Material Document',
                'verbose_name_plural': '3. Study Material Documents',
            },
        ),
    ]
