# Generated by Django 6.0.3 on 2026-08-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_studymaterialexam_studymaterialsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='display_questions_limit',
            field=models.IntegerField(blank=True, help_text='Number of questions to show to the user (e.g. 50). Leave blank to show all.', null=True),
        ),
    ]
