# Generated by Django 6.0.3 on 2026-09-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_quiz_display_questions_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='bulk_upload_json',
            field=models.TextField(blank=True, help_text='Paste JSON array here to bulk upload MCQs. e.g. [{"text": "Q1", "choices": [{"text": "A", "is_correct": true}, {"text": "B", "is_correct": false}]}]', null=True),
        ),
    ]
