# Generated by Django 6.0.3 on 2026-09-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_quiz_bulk_upload_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='banner',
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='apply_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='recentupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
