# Generated by Django 6.0.3 on 2026-09-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_course_banner_alter_jobvacancy_apply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Total duration of test in minutes (e.g. 60 for 1 hour, 120 for 2 hours).'),
        ),
    ]
