# Generated by Django 6.0.3 on 2026-09-17 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_quiz_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solvedpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studymaterialdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pdf_link',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_questions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='solvedpaper',
            index=models.Index(fields=['subject', '-created_at'], name='core_solved_subject_c90589_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialdocument',
            index=models.Index(fields=['subject', '-created_at'], name='core_studym_subject_671058_idx'),
        ),
        migrations.AddIndex(
            model_name='topicquestion',
            index=models.Index(fields=['topic', 'id'], name='core_topicq_topic_i_c01972_idx'),
        ),
    ]
