# Generated by Django 6.0.3 on 2026-09-18 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_choice_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='pdf_link',
            field=models.URLField(blank=True, help_text='Paste Google Drive link or Cloud PDF link here', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. BPSC TRE 4.0 Syllabus PDF', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
